### ISSUE TITLE
Modification needed to work with BERT

### ISSUE THREAD

**Issue by primecai** [jungwhank/rcnn-text-classification-pytorch#3]
Hi,

I'm wondering if this model will work well with BERT embedding? In order to make this modification, we need to change the parameters vocab_size to 30522, embedding_dim to 768, and delete the lines using self.embedding, is there anything else required modification?
I am new to NLP and pls forgive me for such questions.

Many thanks.

**Comment by jungwhank** [comment]
Hi, @HexagonPrime 

I'm not sure performance of this model with BERT embedding because I never tried.
But in my opinion, if u want to use BERT embeddings, I recommend BERT fine-tuning 
if there is no special reason to use this model because this paper is introduced quite a long time ago.

thanks
